import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Home() {
	const router = useRouter();
	const handleOnSubmit = (event) => {
		event.preventDefault();
		const milestone = Array.from(event.currentTarget.elements).find(
			(el) => el.name === 'milestone'
		).value;

		console.log(
			'🚀 ~ file: index.js ~ line 11 ~ handleOnSubmit ~ milestone',
			milestone
		);
		router.push(`/mileston/${milestone}`);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<form onSubmit={handleOnSubmit}>
					<label htmlFor='milestone'>Enter your milestone</label>
					<input type='text' name='milestone' id='milestone' />
				</form>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
